### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by zoranzoki21** [Hutchy68/Purge#10]
Hi,
can I here add translations because L10n-bot does not included translations for serbian language or I have to translate on translatewiki?

If I have to translate on translatewiki, please give me link where I can do it..

Much greetings,
Zoran.

**Comment by zoranzoki21** [comment]
I found where

**Comment by zoranzoki21** [comment]
I have not, where to translate. I will create a pull request with translates.

**Comment by samwilson** [comment]
This extension should be registered on translatewiki.net, then all translations can come from there.

**Comment by zoranzoki21** [comment]
I can not to find where is it

2017-11-01 23:11 GMT+01:00 Sam Wilson <notifications@github.com>:

**Comment by samwilson** [comment]
Oh, no, sorry: I was saying that this *should* be on translatewiki, not that it is yet! @Hutchy68 are you interested in doing so?

**Comment by zoranzoki21** [comment]
My pull requests need to be deployed.

2017-11-01 23:25 GMT+01:00 Sam Wilson <notifications@github.com>:

**Comment by Hutchy68** [comment]
Reopening. Yes let’s add this extension to Translatewiki.net.

**Comment by Hutchy68** [comment]
@kghbln and @samwilson giving this a bit of love today. v1.0.2 is released. 

Looks like `qqq.json` is up-to-date and all I would have to do is add @translatewiki as a collaborator. Just pinging @Nikerabbit into this thread in case I missed something.

**Comment by kghbln** [comment]
I created https://github.com/Hutchy68/Purge/pull/14 to improve the qqq. Should be fine now.

**Comment by Hutchy68** [comment]
I'll merge as soon as the menue and lable is resolved. Also, I do not have an account on Translatewiki.net so I can not open a thread there to ask for translation. I did grant @translatewiki collaborator permissions.

**Comment by kghbln** [comment]
Done. From experience @nikerabbit is pretty fast in responding. Pinging him here should be fine.

**Comment by Hutchy68** [comment]
Ok, I did create an account but can not post to that page anyway.

`You cannot post new threads to this discussion page because it has been protected from new threads, or you do not currently have permission to edit.`

Thanks, then all is good.

**Comment by Hutchy68** [comment]
I merged in #14 and reset the tag v1.0.2 to that that commit. Thanks for the update to `qqq.json` @kghbln

**Comment by Nikerabbit** [comment]
Did you choose the developer sign-up option? In any case I approved your account.

**Comment by samwilson** [comment]
Will this repo have to be moved to Wikimedia before translating works?

https://translatewiki.net/wiki/Translating:MediaWiki#Extensions —
> MediaWiki extensions residing on other repositories (including GitHub) will not be supported. See here for the details. 

And — https://translatewiki.net/wiki/Thread:Support/Add_MediaWiki_Extensions_from_github_to_translation/reply

**Comment by Nikerabbit** [comment]
That's outdated. I have updated the documentation page.

**Comment by Hutchy68** [comment]
Ok, I think this issue is ready to close. Reopen if needed.

**Comment by samwilson** [comment]
The translation link on [Extension:Purge](https://www.mediawiki.org/wiki/Extension:Purge) goes to https://translatewiki.net/wiki/Special:Translate/ext-purge which doens't exist.

**Comment by Hutchy68** [comment]
Looks like it was added to me.

https://translatewiki.net/wiki/Special:Translate/mwgithub-purge

**Comment by samwilson** [comment]
Ah, cool, different name. [Updated.](https://www.mediawiki.org/w/index.php?title=Extension%3APurge&type=revision&diff=2615105&oldid=2608094)

**Comment by Hutchy68** [comment]
Thanks, just saw. Closing this now.

**Comment by zoranzoki21** [comment]
Thank you very much for resolving problem
