### ISSUE TITLE
Move to Gerrit and Phabricator?

### ISSUE THREAD

**Issue by samwilson** [Hutchy68/Purge#20]
What do you think of the idea of moving this extension to a Gerrit repository, so it can take advantage of the [continuous integration](https://www.mediawiki.org/wiki/Continuous_integration) testing?

It'd mean changing the new translatewiki setup, and issue-tracking would be done in Phabriactor.

More info:
https://www.mediawiki.org/wiki/Continuous_integration/Tutorials/Adding_a_MediaWiki_extension

It'd mean this would be managed in the same way as almost all other extensions.

**Comment by zoranzoki21** [comment]
Nice idea

**Comment by samwilson** [comment]
Fair enough. :-)

Should we set up continuous integration testing here (e.g. Travis)?

**Comment by kghbln** [comment]
The reason is that collaboration tends to be easier on GitHub. Since we finally added twn-support for the extension here on GitHub ... In the end it is probably up to @Hutchy68 to decide. 

> Should we set up continuous integration testing here (e.g. Travis)?

Indeed, integration testing should be available, here or elsewhere.

**Comment by Hutchy68** [comment]
>The reason is that collaboration tends to be easier on GitHub.

👍🏻
